### ISSUE TITLE
Add a warning when imageToGround doesn't intersect the body

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/usgscsm#233]
Right now imageToGround in the framer and LS sensor models returns the point on the image ray closest to the body when it doesn't intersect. We should return a warning, via the passed in WarningList, when this happens. See https://github.com/USGS-Astrogeology/knoten/issues/8 for a case in which this is important.

**Comment by AustinSanders** [comment]
Looks like this is closed via https://github.com/DOI-USGS/usgscsm/pull/311
