### ISSUE TITLE
Need a release

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/usgscsm#444]
The USGSCSM needs to be released. There are have been multiple updates to the library that fix issues with the Kaguya sensor model that have not been released. Other libraries link against the CSM (statically and dynamically, I believe) and those libraries do not have access to these fixes.

Additionally, the inclusion of a `proj` dependency breaks usage by these libraries. So, prior to release, the `proj` dependency needs to be fixed.

This is exceptionally time critical.

**Comment by thareUSGS** [comment]
I agree that the inclusion of PROJ has been problematic. Not sure how to move forward, perhaps make PROJ optional? But requiring the proj library (which also needs sqlite and curl) along-side the usgscsm and ale libraries has a large potential to conflict with applications like GXP. GXP has its own version of PROJ already.

**Comment by oleg-alexandrov** [comment]
I recall that when installing ISIS with conda the proj library gets
installed as well, so ISIS depends on it too through some library. So do
GDAL and ASP, and each GDAL version is tied to just a range of PROJ
versions.

So I agree that if one can avoid using PROJ in usgscsm, that should make
things easier for everybody. Or at least it should be quite a recent
version so that a recent GDAL can be used with it. I guess one could check
what version GXP uses and if it is being kept up-to-date.

Not sure what PROJ is used for. I recall in CSM one normally would just use
ECEF rather than any particular projection.

**Comment by thareUSGS** [comment]
PROJ was included to allow for "map projected" stereo. This was tested as a "just in case" need for Europa Clipper EIS (imaging pushbroom). Given that Europa Clipper is a fly-by mission, single images will be widely varying in resolution (e.g., [Cassini SAR](https://atmos.nmsu.edu/data_and_services/atmospheres_data/Cassini/inst-radar-sar.html)). To collect stereo, the images might need to be map projected on a sphere before collection. For the initial usgscsm test, PROJ was used to support the Oblique Cylindrical projection. The Obl. Cylindrical project "could" be hard-wired I guess. Now, I am a fan of using PROJ but perhaps not currently how it is released.

I don't think the impact for a temporary removal of PROJ from usgscsm would be a large impact as EIS is still under development and we are awaiting synthetic data for testing. Mission is going to take a several more years to get there!

**Comment by acpaquette** [comment]
@jlaura @thareUSGS @oleg-alexandrov can this be considered finished once that ASP release goes out?

**Comment by oleg-alexandrov** [comment]
On my side I can confirm that newly-minted usgscsm version 1.7 built with proj 9.1.0 plays nice with ISIS 8.0.0 and ASP, and after testing with linescan, frame, pushframe, and SAR datasets.

**Comment by acpaquette** [comment]
@jlaura ALE isn't integrated yet but I can get that PR rolling and fixed on linux. Is that something we want to see happen?

**Comment by jlaura** [comment]
@acpaquette  I don't know that we need to rush it. Right now the windows CI builds ALE and USGSCSM and then uploads them as build artifacts. That should be working for @thareUSGS (can you please confirm?).

Is the plan to get all `usgscsm` dependencies in the binary? If so, I think waiting to roll that for all platforms makes sense.

Also - I am going to close because this is done from my perspective. We are tracking the windows build in #441 and the M1/M2 architecture in #443. Please reopen if anyone disagrees!
