### ISSUE TITLE
Help needed: absolute triangulation HiRISE SOCET GXP

### ISSUE THREAD

**Issue by marlens123** [DOI-USGS/usgscsm#456]
Thank you for providing this great repository!

I am currently working on an internship project on DEM generation from HiRISE using SOCET GXP. I am new to the software and am trying to figure out the processes. In particular, I am wondering how I can obtain and integrate MOLA data for absolute triangulation. I am currently downloading MOLA PEDR data from https://ode.rsl.wustl.edu/mars/datapointsearch.aspx and MOLA DEM from https://astrogeology.usgs.gov/search/map/Mars/GlobalSurveyor/MOLA/Mars_MGS_MOLA_DEM_mosaic_global_463m. However, when I integrate the files into the triangulation process, no control points seem to fall on the images, although the coordinates should match.

Seeing that many of you have experience with HiRISE in SOCET GXP, I was wondering if you have tips or resources for this?

I highly appreciate your support!

**Comment by thareUSGS** [comment]
For GXP questions, the best methods for questions is via our email "planetaryphotogrammetry at usgs.gov" or direct emails. There is also Open Planetary forum: https://www.openplanetary.org/

Anyway, MOLA topography can be extracted from the file above for GXP. While map projected GeoTIFFs seem to work, we still often import the clipped area to an Arc ASCII grid format (using GDAL) in degrees. Likely the easiest method to clip from the MOLA is visually in QGIS or using gdal "-projwin" parameters. GDAL can be a little tricky if you want to clip a file in a projected meters using Long/Lat bounds. But you can do that using gdal_translate (projwin and projwin_srs) or gdalwarp (te and te_srs).

e.g.;
> [gdal_translate](https://gdal.org/programs/gdal_translate.html) -projwin 120 45 115 40 -projwin_srs IAU_2015:49900 MOLA_in_meters_projection.tif out_clip.tif

Here you are clipping by a lon/lat range defined by the projwin_srs set to Mars in degrees. [IAU_2015:49900](https://spatialreference.org/ref/iau_2015/49900/).

or (exporting to ASCII for GXP ASCII terrain import using degrees)

> [gdal_warp](https://gdal.org/programs/gdalwarp.html) -te 115 40 120 45 -te_srs IAU_2015:49900 -of AAIGrid MOLA_in_meters_projection.tif  out_clip_degrees.asc

note the order of "-te" is different from gdal_translate's "-projwin"

To go from elevations in "topographic" heights to "geoid" heights (optional but recommended) you can run ASP's [dem_geoid](https://stereopipeline.readthedocs.io/en/latest/tools/dem_geoid.html).
