### ISSUE TITLE
Bundle Adjustment support 

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/usgscsm#457]
This issue is for tracking progress on adding CSM bundle adjustment support. 

DoD is code being PRed that can produce a simple bundle adjustment solution.

**Comment by oleg-alexandrov** [comment]
Is this meant as a tool within the CSM library?

**Comment by Kelvinrr** [comment]
@oleg-alexandrov probably not, this is probably something more for knoten. I'll probably move the issue there.
