### ISSUE TITLE
Landed Sensor Support

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/usgscsm#458]
This is part of tracking progress for landed sensor support. 

DoD is a PR being merged with some robust solution for a grounded sensor.

**Comment by Kelvinrr** [comment]
Some of this was completed already, we should link whatever work was done here.

**Comment by jlaura** [comment]
@Kelvinrr  I think we can close with the merge of [#580 on ale](https://github.com/DOI-USGS/ale/pull/580)

**Comment by Kelvinrr** [comment]
@jlaura Im going to be a stickler and say that the landed sensor support is only concerning USGSCSM. I personally I think this is complete as far as how it's written. But we should still get an issue on ISIS for what ISIS needs to leverage the new changes, and we can still target those changes in upcoming sprints. I'd appreciate if you make the issue over at ISIS.

**Comment by jlaura** [comment]
Done: https://github.com/DOI-USGS/ISIS3/issues/5370
